#!/bin/bash

options=(
    # round or square
	style=round
	width=3.0
	hidpi=on
    ax_focus=on
    # catppuccin
    #active_color=0x00ff99ee
	#active_color="gradient(top_left=0xff89b4fa,bottom_right=0xff89b4fa)"
    # hyprland
	active_color="gradient(top_left=0xffff99ee,bottom_right=0xffccffee)"
    inactive_color=0xff414550
    # hyprland
	#inactive_color=0xff444444
)

borders "${options[@]}"
