[settings]
animate = false
animation_duration = 0.2
animation_fps = 60.0

default_disable = false

focus_follows_mouse = true
mouse_follows_focus = false
mouse_hides_on_focus = true
auto_focus_blacklist = []

run_on_start = []
hot_reload = true

[settings.layout]
mode = "traditional"

[settings.layout.stack]
stack_offset = 0.0
default_orientation = "perpendicular"

[settings.layout.gaps]
# - outer: space between windows and screen edges
# - inner: space between tiled windows

[settings.layout.gaps.outer]
top = 0
left = 0
bottom = 0
right = 0

[settings.layout.gaps.inner]
horizontal = 0
vertical = 0

[settings.ui.menu_bar]
enabled = false

[settings.ui.stack_line]
enabled = false
horiz_placement = "top"
vert_placement = "left"
thickness = 0.0
spacing = 0.0

[settings.ui.mission_control]
enabled = false

[settings.gestures]
enabled = true
swipe_vertical_tolerance = 0.4
skip_empty = false
fingers = 4
distance_pct = 0.08
haptics_enabled = true
haptic_pattern = "level_change"

[settings.window_snapping]
drag_swap_fraction = 0.3

[virtual_workspaces]
enabled = true
default_workspace_count = 5
auto_assign_windows = true
preserve_focus_per_workspace = true
workspace_auto_back_and_forth = false

app_rules = [
    { app_name = "System Settings", floating = true },
    { app_id = "com.apple.systempreferences", floating = true },
]

[modifier_combinations]
comb1 = "Alt + Shift"

[keys]
"Alt + H" = { move_focus = "left" }
"Alt + J" = { move_focus = "down" }
"Alt + K" = { move_focus = "up" }
"Alt + L" = { move_focus = "right" }

"comb1 + H" = { move_node = "left" }
"comb1 + J" = { move_node = "down" }
"comb1 + K" = { move_node = "up" }
"comb1 + L" = { move_node = "right" }

"Alt + 1" = { switch_to_workspace = 0 }
"Alt + 2" = { switch_to_workspace = 1 }
"Alt + 3" = { switch_to_workspace = 2 }
"Alt + 4" = { switch_to_workspace = 3 }
"Alt + 5" = { switch_to_workspace = 4 }

"comb1 + 1" = { move_window_to_workspace = 0 }
"comb1 + 2" = { move_window_to_workspace = 1 }
"comb1 + 3" = { move_window_to_workspace = 2 }
"comb1 + 4" = { move_window_to_workspace = 3 }
"comb1 + 5" = { move_window_to_workspace = 4 }

"Alt + Tab" = "switch_to_last_workspace"

"Alt + Comma" = "toggle_stack"
"Alt + Slash" = "toggle_orientation"

"Alt + V" = "toggle_window_floating"
"Alt + Shift + F" = "toggle_fullscreen"

"Alt + Equal" = "resize_window_grow"
"Alt + Minus" = "resize_window_shrink"
