[font]
normal = { family="Iosevka Nerd Font", style = "Regular" }
size = 13

[window]
padding = { x = 8, y = 8}

[general]
live_config_reload = true
import = [
"~/.config/void-theme/current/alacritty.toml"
]

[env]
TERM = "xterm-256color"
